version: "3"

services:
    db:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - mongo_kea_data:/data/db

    app:
        container_name: app
        build: .
        command: npm start
        restart: always
        depends_on:
            - db
        ports:
            - "3000:3000"
        environment:
            - MONGO_HOST=db
            - MONGO_DB=kea
    
    mongo-express:
        image: mongo-express
        depends_on:
            - db
        ports:
            - "3001:8081"

volumes:
    mongo_kea_data:
