version: "3"

services:
    db:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - mongo_kea_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example